apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: descheduler
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: descheduler
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: descheduler
      interval: 12h
  values:
    schedule: "0 9 * * *"
    successfulJobsHistoryLimit: 1
    failedJobsHistoryLimit: 1
    deschedulerPolicy:
      profiles:
      - name: RemoveDuplicates
        pluginConfig:
          - name: RemoveDuplicates
            args:
              namespaces:
                exclude:
                - "kube-system"
          - name: RemoveDuplicates
        plugins:
          balance:
            enabled:
              - RemoveDuplicates