apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: descheduler
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: descheduler
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: descheduler
      interval: 12h
  values:
    schedule: "*/5 * * * *"
    deschedulerPolicy:
      profiles:
      - name: RemoveDuplicates
        pluginConfig:
          - name: RemoveDuplicates
            args:
              ignorePvcPods: false
              evictLocalStoragePods: true
              namespaces:
                exclude:
                - "kube-system"
          - name: RemoveDuplicates
        plugins:
          balance:
            enabled:
              - RemoveDuplicates