apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: descheduler
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: descheduler
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: descheduler
      interval: 12h
  values:
    service:
      enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus-stack
    kind: Deployment
    deschedulerPolicy:
      profiles:
      - name: default
        pluginConfig:
          - name: RemoveDuplicates
            args:
              evictLocalStoragePods: true
              namespaces:
                exclude:
                - "kube-system"
        plugins:
          balance:
            enabled:
              - RemoveDuplicates