apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: descheduler
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: descheduler
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: descheduler
      interval: 12h
  values:
    service:
      enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus-stack
    kind: Deployment
    deschedulerPolicy:
      evictLocalStoragePods: true
      profiles:
        - name: default
          pluginConfig:
            - name: DefaultEvictor
              args:
                evictLocalStoragePods: true
            - name: RemoveDuplicates
          plugins:
            balance:
              enabled:
                - RemoveDuplicates