apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: nfs-csi
spec:
  interval: 30m
  chart:
    spec:
      chart: csi-driver-nfs
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
      interval: 12h
  values:
    storageClass:
      create: true
