apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: controller-manager
  namespace: actions-runner-system
spec:
  encryptedData:
    github_token: AgAnmmW3ncBoTwuFNB973UKgMHNmg7cuS0KdPIVVplSw/f7+xg9WbFxr88zxH3NSfOlKJ1SRbZN4VYGKhkeABoJz75rXZXro76g956aLqQ+DQF1CQO3GvWSLZd63ic12jGrsqbniHTDNb5GAYxH9HaX5/QBMCNoJdjueKMd7xwRGEb/dfhCh0ZT1xn44BTXTFExvbtrkB42jDVoBnaYVU1HtU23aTseXLHQ4myPOr1iEn70IRZKizkCkAA/DO1iUMelYr+TbA2RcI7R5CrGsrlCIRag3IyJnCV2iGLx0LD0FSpqCuJVuCJSqr04Qihw9jGHwtAxoM8jxXdcrVXZZrLy4/MZGulAPdgjeeyAUjM8Te/CUoGjSSZMY9qgwDDudEydjYqZhgm6sO0sxQd71ztgzfbqFV23w7Xz9YvFZTIV6cvI/GJuk/0aqn5YRg9MirB5xJUso618mQjlLIRcrSboOWVkfQPVF0HljonHBbatgfE/hw2ne1drRtEE2Oc2XpD+VPITe6+/o/l+HeYRXm/1cC9gjfBhaPfcRDdTj35/uZ8lC+qXCjhYSXpSjgJftzWHDyntlb23MyZw5ZsU9xkLcoPR5V/4bAHUVRstYzrpFmb0mQe6Eto/BdIhAEGyUDk+btwS+dHpRJj/GxKP7tRp2byEsw46S6GPvafpGZ3hJv2d4PWrL0wX7U+9634Unp03FB9nZNysyKiaijBPI75beXa2yJ5i534qtqLrcoPRSs7foRBBeulsi
  template:
    metadata:
      creationTimestamp: null
      name: controller-manager
      namespace: actions-runner-system