apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: cloudflare
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: external-dns
      interval: 12h
  values:
    sources:
      - ingress
    policy: sync
    provider:
      name: cloudflare
      env:
      - name=cloudflare
      - valueFrom.secretKeyRef.name=cloudflare-api-key
      - valueFrom.secretKeyRef.key=apikey
