apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflare-tunnel
  namespace: cloudflare
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudflare-tunnel
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: cloudflare-tunnel
      interval: 12h
  values:
    cloudflare:
      tunnelName: "K8s-Homelab"
      tunnelId: "b4370153-d4e8-40b9-a248-e5a0b8cb2800"
      secretName: "tunnel-credentials"
      ingress:
        - hostname: "*.homek8s.cloud"
          service: "https://ingress-nginx-controller.ingress-nginx.svc.talos.home:443"
          originRequest:
            noTLSVerify: true
    resources:
      limits:
        cpu: "100m"
        memory: "128Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"