apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgCGxo8L+0yB7a+l7pZdbSMYf394YMKf77EnTdKve9MyGqi2XKIMgZG/y+IlmI/l1Ljez1Hghmdpj0LpFWdyLGHIEheQ9QWQih1TIWox/xIjA+75jDNFy3NpHvdgSssrONrBet5y2ECZD340E2CpOP+t41tXPivh8DujFwY4/to9jsGYAkkFpptPogfbwkGjym5O8X6EE3R/t2jxz2QWAN3uRicHdGC6bSd+3I8Pctpx/lmIHFFFrxll9cXg1mIEvZySdVj5qpTvo7kV6TaObYvF1yRdKTi9zpQkTew5Gj9AXixAGb6CNhc8sZJV3cPezsvDdcDugE4AGOlce1DbLGbAzAsRJrgB7gNJlWc0GonGd929eXZ25FINIVxu+HYAgeDNPp3grDlyTkU+VmmLklKdTWqQ/jw6JVYr7PIhduu9y6mjEL66qnH2KgXJOz1iJ+Q8AKd9RHIhRT1Curp9eCZurJFg9e0HeY+l60ofPFNGYqWsc4mGCCHRHklLIiddUiuhvK1YjpOvS37TuzF3OBpeQ+kSRZ54pitxbBiH//OtUoRdKhj+5H9l9/Fx49pZEopCuhjoIQihQ+6SK4PDB7jwCG32X6WpYKq9UWTJ5vP1+LkyNUtYQDkKNltISWLSQp9kYFRq4/iVaj0DgrTX45dsx5QfG3UYDPp01peHPLXR7WZwq2j1MiHw3RaHFFzUUWZ+RBaaeNf2XLnUJpeoYYSHeyo7CXoL5YMvgfdDab0W+at5xOZnmGYbjuCkW/nbzFg8E78uNUwc8yEEAeHYAH4lKha3OTRAsDrHyncQweYf7VtRTnrtjSPV7oBqBSaSzLrPvF52zmkDrje6QLd7umFKckjVL9QxnrQpeZfcIBo9VNB7rcVvhlJmRliwVM6CPNvJXuXqXdhDxsVArP5MrorNYg==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare