apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  interval: 30m
  chart:
    spec:
      chart: oauth2-proxy
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
      interval: 12h
  values:
    config:
      cookieName: "oauth2-proxy"
      configFile: |-
        provider="keycloak-oidc"
        provider_display_name="Keycloak"
        redirect_url="https://oauth2-proxy.homek8s.cloud/oauth2/callback"
        oidc_issuer_url="https://keycloak.homek8s.cloud/auth/realms/homelab"
        code_challenge_method="S256"
        ssl_insecure_skip_verify=true
        http_address="0.0.0.0:4180"
        upstreams="file:///dev/null"
        email_domains=["*"]
        cookie_domains=["homek8s.cloud"]
        cookie_secure=false
        scope="openid"
        whitelist_domains=[".homek8s.cloud"]
        insecure_oidc_allow_unverified_email="true"
    auth:
      existingSecret: oauth2-proxy-secret
    sessionStorage:
      type: redis
      redis:
        existingSecret: oauth2-proxy-secret
        passwordKey: redis-password
    redis:
      enabled: true
      architecture: standalone
      auth:
        existingSecret: oauth2-proxy-secret
        existingSecretPasswordKey: redis-password
    ingress:
      enabled: true
      className: "nginx"
      pathType: Prefix
      path: /oauth2
      annotations:
      hosts:
        - oauth2-proxy.homek8s.cloud