apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 30m
  chart:
    spec:
      chart: keycloak
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: keycloak
      interval: 12h
  values:
    global:
      storageClass: longhorn
    production: true
    proxy: edge
    resourcesPreset: "medium"
    auth:
      adminUser: admin
      existingSecret: keycloak-admin-password
      passwordSecretKey: password
    postgresql:
      enabled: true
      auth:
        existingSecret: keycloak-db-credentials
      primary:
        persistence:
          enabled: true
    ingress:
      enabled: true
      ingressClassName: "nginx"
      pathType: Prefix
      hostname: keycloak.homek8s.cloud
