apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crossplane
  namespace: crossplane
spec:
  interval: 30m
  chart:
    spec:
      chart: crossplane
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: crossplane
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
