apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-thanos
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: thanos
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: kube-thanos
      interval: 12h
  values:
    clusterDomain: talos.home
    existingObjstoreSecret: "thanos-objstore-config"
    query:
      resources:
        limits:
          cpu: 200m
          memory: 2Gi
      enabled: true
      stores: 
      - kube-thanos-receive-0.kube-thanos-receive-headless.monitoring.svc.talos.home:10901
      - kube-thanos-receive-1.kube-thanos-receive-headless.monitoring.svc.talos.home:10901
      - kube-thanos-receive-2.kube-thanos-receive-headless.monitoring.svc.talos.home:10901
      replicaLabel: [prometheus_replica]
    ruler:
      enabled: true
      replicaLabel: prometheus_replica
      persistence:
        storageClass: "longhorn"
        size: 8Gi
      alertmanagers:
      - http://prometheus-stack-alertmanager.monitoring.svc.talos.home:9093
      existingConfigmap: thanos-ruler-cm
      clusterName: "talos.home"
    bucketweb:
      enabled: true
    compactor:
      enabled: true
      extraFlags:
      - --deduplication.replica-label="prometheus_replica"
      - --compact.enable-vertical-compaction
      #- --deduplication.func=penalty
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
      retentionResolutionRaw: 7d
      retentionResolution5m: 14d
      retentionResolution1h: 30d
      persistence:
        storageClass: "longhorn"
        size: 20Gi
    queryFrontend:
      enabled: true
      config: |-
        type: IN-MEMORY
        config:
          max_size: 250MB
          max_item_size: 125MB
      extraFlags: 
      - --query-range.split-interval=24h
      - --query-range.max-retries-per-request=3
      - --query-frontend.log-queries-longer-than=60s
    storegateway:
      enabled: true
      persistence:
        storageClass: "longhorn"
        size: 10Gi
    receive:
      enabled: true
      persistence:
        storageClass: "longhorn"
        size: 8Gi
      service:
        additionalHeadless: true
      resources:
        requests:
          cpu: 150m
          memory: 150Mi
        limits:
          cpu: 200m
          memory: 2048Mi
      mode: dual-mode
      tsdbRetention: 7d
      replicaCount: 3
      config:
        - endpoints:
          - "kube-thanos-receive-0.kube-thanos-receive-headless.monitoring.svc.talos.home:10901"
          - "kube-thanos-receive-1.kube-thanos-receive-headless.monitoring.svc.talos.home:10901"
          - "kube-thanos-receive-2.kube-thanos-receive-headless.monitoring.svc.talos.home:10901"
      replicaLabel: prometheus_replica
    receiveDistributor:
      enabled: true
      replicationFactor: 3
      resources:
        requests:
          cpu: 150m
          memory: 150Mi
        limits:
          cpu: 200m
          memory: 1024Mi
      replicaLabel: prometheus_replica
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: "monitoring"
        labels:
          release: prometheus-stack
      prometheusRule:
        enabled: true
        default:
          create: true
          namespace: "monitoring"