apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thanos-query-frontend-ingress
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/auth-signin: https://oauth2-proxy.homek8s.cloud/oauth2/start?rd=https://$host$request_uri
    nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy.oauth2-proxy.svc.talos.home/oauth2/auth
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
spec:
  ingressClassName: nginx
  rules:
  - host: thanos-query.homek8s.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kube-thanos-query-frontend
            port:
              number: 9090
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thanos-bucket-ingress
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/auth-signin: https://oauth2-proxy.homek8s.cloud/oauth2/start?rd=https://$host$request_uri
    nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy.oauth2-proxy.svc.talos.home/oauth2/auth
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
spec:
  ingressClassName: nginx
  rules:
  - host: thanos-bucket.homek8s.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kube-thanos-bucketweb
            port:
              number: 8080