apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth-prometheus
  namespace: monitoring
spec:
  encryptedData:
    auth: AgC+juNoKtyaFDdb43Hpndqgk5wvToXU+Zh50GZCmWPibwo1a0c7URFizUKR28+1R1X9/qWzvCp844eHMEKY65YNGobnI3cvvVTkoSNRw9x01VLHg6qjXPqkHxGmEPK2ZgeEeY2Vzd4D1+Z5auv0WugpgwYuNmApbGOCMvunwo7DA7ocyE+AmqYIZV0jyFZUm0hJ+Q+vhjRoRwdC0d37dQ+gniOqtCSZIjlLEEo4ykOiFlsV9loZPnTqe7v6w3zF7NIOm9vo7n0UO6oODhedBBwe9UZVzU6F5dk9nZRCJi2gY1EIHVIvElK68DHHnqIF1MNPoV6OpUMkFlDgPwjlIW4gupGw12WBH1cbJnneB5t6KtkFjws4B2C4Z1qxjguBiBA5xnhXar3NxOiCMvnOpCS9P3D2/10vD0j/Nf78elyZvTxxn1U/PBAaGJRYg89EMa0zHP2iphTDBnO36/KeguTOPTc33kr9C+jFuHc/FtuNXZq/JPcPkMPgScWeZdfEs0ztQ9p/2RWolJnPO0fZOcELBnYrm5Gjec8TdUJTcxvkYmBr8z/jDggSeeJTLLcU4s2HeZMaPpOzA9eYTXTzu+3eHpmArdeH4qjwScU0I1mA4hbilqUvDvhPKL/2/pvN8Ohvb36iBh4/bhPbMQsfMB77BAaHizFoCSUcwdjSsJo5nrg5magnjy8fqE4qK7NYgsAL04KNrCACDejpB4Gx3vFDdtY0z1aUjE3isluWXLf4DRMc21yiz6bYC3xrdQ==
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth-prometheus
      namespace: monitoring