apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
      interval: 12h
  values:
    fullnameOverride: "prometheus-stack"
    defaultRules:
      create: true
      rules:
        alertmanager: true
        etcd: true
        configReloaders: false
        general: true
        k8sContainerCpuUsageSecondsTotal: true
        k8sContainerMemoryCache: false
        k8sContainerMemoryRss: false
        k8sContainerMemorySwap: false
        k8sContainerResource: true
        k8sContainerMemoryWorkingSetBytes: true
        k8sPodOwner: false
        kubeApiserverAvailability: true
        kubeApiserverBurnrate: false
        kubeApiserverHistogram: true
        kubeApiserverSlos: false
        kubeControllerManager: false
        kubelet: true
        kubeProxy: false
        kubePrometheusGeneral: true
        kubePrometheusNodeRecording: false
        kubernetesApps: false
        kubernetesResources: true
        kubernetesStorage: true
        kubernetesSystem: true
        kubeSchedulerAlerting: false
        kubeSchedulerRecording: false
        kubeStateMetrics: true
        network: true
        node: true
        nodeExporterAlerting: false
        nodeExporterRecording: true
        prometheus: true
        prometheusOperator: true
        windows: false
    grafana:
      persistence:
        enabled: true
        type: pvc
        storageClassName: "longhorn"
        accessModes:
          - ReadWriteOnce
        size: 20Gi
        finalizers:
          - kubernetes.io/pvc-protection
    alertmanager:
      alertmanagerSpec:
        useExistingSecret: true
        replicas: 2
        storage: 
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeEtcd:
      endpoints:
        - 192.168.219.71
        - 192.168.219.72
        - 192.168.219.73 
    prometheus:
      thanosService: 
        enabled: true
      thanosServiceMonitor: 
        enabled: true
      prometheusSpec:
        disableCompaction: true
        externalLabels:
          cluster: talos.home
        retention: 5d
        replicas: 2
        shards: 2
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi
            selector: {}
        thanos:
          objectStorageConfig:
            existingSecret:
              name: thanos-objstore-config
              key: objstore.yml  
