apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: thanos-objstore-config
  namespace: monitoring
spec:
  encryptedData:
    thanos.yaml: AgA8qMI+WQ0BVk5BTwKyq0pC9lpDxmmygIX85o5YF+QvmsAseo0i4xY3DhKVb9rBaQdLRvgRbjIMt/XKGlPQR3MXnX4F0KTsK5SWKwUyjpoCi78x9lSRNVxyA/OkSj+eJhz/YbbdqClKwMduxqy7DScC6FYwALblA7KLuYIgxh7z4zqzkFobQLMoCR8a1FgjgYlwlLshE4SvS+1783+s9OgT6RJS3j53Oat6BH3ZO/0ZY+6+gHoGAoGNkc3OCdM7QnV3BiycBW/zi0K9srnRrTB1M1HXebpdogaCT/dhxlp6fLG4TFaL4d/p9CQXipKpN9+w+nB+Rstv1jDAiHmV81P8iL2P6gyIxu2JqWvCuMjQ7SpOSU1J/61q4N0qf7IHk9HUKAaC1kmPhKHqFn+KWVCNVC1V63Vr8k7CrpgW5ftaEJMwn57UQwSlYthKDYS9DLxyBUsuaB4yCjqpEwwSfxHsFMlnSWAxDXiOJISfm7xaOWUboTb3EuKc8o290sQgClPKqUYq+pnBlMMjmGMTGHrAVsiF7R1VwEVXUHf4d4rewFKJ/fgTXVzH7G7HFIVNdwyW7Qop05FREKtWp9l+S5deIhi+OS/E0j0V0mxmsJuNxatirqeL6FcMaCg8foL622q1tBNER3um/QKr9/xWweY70p+KvFAUcTfBGjVgUKCU5PI4gZ8d68XfGEpVmLPiC38oZkELkKA3MJQYcfsCTKBByWe6VF+6EW9hXRc6bi51u01+3cdhxhcZMlSluj6N+opOaMt1oexidGCuzCKYZR4NEoQoQwvvyuMIjBcvWwaOq7m8M2vAiWz9BI2+ReskIl77zY/GpGefDb+e+RWUYnz0ExxqkqNklN3mfyNHm9j4MfugbISIEp1Bx/bZc3/uhefpZDeOHg==
  template:
    metadata:
      creationTimestamp: null
      name: thanos-objstore-config
      namespace: monitoring