apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: thanos-objstore-config
  namespace: monitoring
spec:
  encryptedData:
    thanos.yaml: AgCByYoYHGKi6fIqKXe3XTltsKFJJV9uisOtTLH+1e3GXFx9FskIyqjmA5t5S3khOh07nMfcnWtTWQilZaZxtb3M6baSXawcrRsrl6GqFJ2PD126fL25Aa7FDCer2bTdZMxjGiRuQcgxP1aoPxG0ICQ00DuEiWq/e3Oz8VE+zNZPIGZsJHTeO4O/aGHNF08PAWqquQ3ALAoar9ahKFPtmqJBeZH01sRcf9B3izY4Hm74ID6Dv7KPkNcSvGvPx/LFAe2asb23UuZupbsEh47tRMznInZzwHVEroL5ViBUTzEB8e5o4JOvbO8hlVSYLAy9xoUG1qw/43uIoedJxtQwOtrKObCKoIU2ekC4kzZcjZGivuzogRREIxNpsfjGZzfDvZP17BFJPhLAbLcQrT/Ri2cQUbV5Qu5trboHjFSVhLYx+BDB+PPvV3NmJFPCRqfSWYkLKqKV8Devp2yCb6rlH7ZMzgK5do7BtVkl6ppsyF6idkVGmnY1DjedVYTZTMGyPGNCtfC4B4eOkp9zFPlX+eSxfk6KAXBiO8kdR3vpuV4hoJkzUqHRmvMO4Gksx33GbvESMzqQrbIqHMbrImEOtmb8b2+NR4HiuV3FcOW4xyQ7tDShNDq5NBxqRWpX4WF5aubYD5ISuzC0PJAtrqv6pJBGYT1iz38RPmliOxTOVJOhEC7HvMG0rgJtmUUx+O3S8zZwac49POEXRBXv37cLfFIlIcdASkq/vmblqnfZDAzXy54TC5IcwCiW5ztq/YH3IpFVD5XQfQbf0pcf+JxC4d1kNbGYfFAOxcTxrByUcfn4p7wBmthm+R/tufeMAg6t9SzIPAMajOaAF/RWJypGkKqjZXGqji605D4/1wcfpcQq
  template:
    metadata:
      creationTimestamp: null
      name: thanos-objstore-config
      namespace: monitoring