apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: thanos-objstore-config
  namespace: monitoring
spec:
  encryptedData:
    thanos.yaml: AgDAXZxTU1+TmPZ/USFzPc/33DaaIFA7VsJj3V1SBk0VssChiFLuAz45equkMMqoiz4KlNY09AcoKCYihGfhpGCuQ53QtGsfMKjXJa7gPs0ejVG04I5Twqu3jHr3oxBKh2WgBdgWK2h8w36rquFs1sk26428sH6MkMzEF5JQour043lqR2xyOmOtvAoYt4v5yCV2vJ5DGGv0cnh95RCGaWaPsnmYTA8L9zCDCKtTBfEbq5ejcK7KuJJJY4mBfEzBWllZjFO6ceS1IHMfxgWup+RNJTrA8BMTMeZaAr7ANAXXXf+hCQPVTMbBBGYkKJznG7GCOR61mPBPuM47OlVW2Q4qozqJqxtUo9uuoMQet2sQezqDWAFHfdt+IhtGUc54iALZltYp5lFusuoM0cv0/EAQsOj0XIqiy3GxkHC3SGUsbKwZ1jSxWb7S3RrklnL9ZQb7YFy5/LrC7aujTsPMk8ujiUbLcAPj5bRQEU68WYICggpUt2iugQIdsW6VfzIPY5hK+vm5tZ8cBWpxwMfNBmhkqJd2nisChHkNeV4jCyFB+d/nlFURzf894KniYleEg8B6XwGs/h8YlRH4PzOhM/OB4yyeM3t/+SJRAcQiyHoMI5Z/TwTIbFwU7AXyfTpskXUcLFp9XuF5KsOmIGfUIgWLGuhowq/TO2V8Hh43N964IulQJT7RZmrVYXyip9CnBqYgsh9pzzHXVYK4IM8xxSDTzzd9va8k7y/MDgM4btrroEZ1rlvGmE8gzvL42hvQ6gVTGSpDq+Kdi01NNvAMVnE9pz9Sf2ULxQ0E+uPhauLvcJ1+tcTswPQ/i6zMMUG9aLwUss0Xi3Cs8Cv+ebDzZ3cSRwT2Ajb2zTdHx6Vp0cNr/pFemmH31ew0RkeU
  template:
    metadata:
      creationTimestamp: null
      name: thanos-objstore-config
      namespace: monitoring``