apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: twingate
  namespace: twingate
spec:
  interval: 30m
  chart:
    spec:
      chart: connector
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: twingate
      interval: 12h
  values:
    hostNetwork: true
    connector:
      logLevel: "error"
      network: "wajiwos14"
      existingSecret: "twingate-secret"