apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: cilium
      interval: 12h
  values:
    k8sServiceHost: localhost
    k8sServicePort: 7445
    securityContext:
      privileged: false
      seLinuxOptions:
        level: 's0'
        type: 'spc_t'
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        mountCgroup:
          - SYS_ADMIN
          - SYS_CHROOT
          - SYS_PTRACE
        applySysctlOverwrites:
          - SYS_ADMIN
          - SYS_CHROOT
          - SYS_PTRACE
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
    l2announcements:
      enabled: true
    externalIPs:
      enabled: true
    socketLB:
      hostNamespaceOnly: true
    hubble:
      peerService:
        clusterDomain: talos.home
      ui:
        enabled: true
      relay:
        enabled: true
    ipam:
      mode: kubernetes
      operator:
        clusterPoolIPv4PodCIDRList: ["172.31.0.0/16"]
    k8s:
      requireIPv4PodCIDR: true
    kubeProxyReplacement: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
        labels:
          release: prometheus-stack
    operator:
      replicas: 1
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
          labels:
            release: prometheus-stack
    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup