apiVersion: networking.cfargotunnel.com/v1alpha1
kind: ClusterTunnel
metadata:
    name: cloudflare-cluster-tunnel
spec:
    newTunnel:
        name: my-cluster-tunnel
    size: 2
    cloudflare:
        email: ENC[AES256_GCM,data:R9PXj4H/R/tmWAv+/UrPkpALlw==,iv:53gcyVYALzdGRf1p0wotrjT7r1eLs3BmuwqWlYNJ4zQ=,tag:VPa0nzHfbKKmNKwJfKRR7g==,type:str]
        domain: ENC[AES256_GCM,data:G8F3CvOZ7VET7CTkxw==,iv:Q5Qdpv7TgrL9wx7DbEakTjwh7cvlGgrIfm01nICAbpY=,tag:XFrDuSQIO+7olj8NImq7fQ==,type:str]
        secret: ENC[AES256_GCM,data:7Bh3WYaWA3k1blXfAwc0jL9V,iv:OVmGDaZs0/kmcC3P1GAiVlkxefYczBFyZY5BJjpdJ9w=,tag:lyDzz33vM5WZ0CRt9w8XUQ==,type:str]
        accountName: ENC[AES256_GCM,data:ARv9NIt9p62hraLNsCXnHxm3Mw==,iv:FXqDaCCwttpSP5/w4LUI59NRLBhMY0kKQMKN/witQSc=,tag:rxkHsbJZaQ5s5pBxeDo7OA==,type:str]
        accountId: ENC[AES256_GCM,data:TDdLKu8iWhhw7zwyERxkCWUrFq83PnnGsZkj38VI9I0=,iv:HzmXQ90aIqOzvSsQ4WRK8pFmVqxqA948A/URSVVS2nE=,tag:q8Uhjz0DhcjZbhUjxr6v5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zxeuqw0a02arkhj3fv4xexz0agnvts0520msa6r4pk7mnp4dee6q4tqsmf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxeHVRVDJOV28yNkxHREwy
            TEh4YnE5dzVnaDVYem8yWnBNTVVTcHMvTkJzCnVQNFBUK0o4ZDMvRGZSUmUxdFNE
            ZVdYOU5DZjdZR1piTlprc2YrVVRFY3cKLS0tIFpBdm5uQXBHZmduQjlRMktZbjU0
            bjhPUE9YRkJXZERvM2JJeUloWUhOU3cKEjFFzB4gG0YdnQGLVfEP74x8agg5NkFh
            s+m1aJIG7jTTRyscnV98PlzlLqz81Jm9CKimor+Ch5tE8Ysv43Llug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-05T14:20:17Z"
    mac: ENC[AES256_GCM,data:G+aTzkKe/gRZuuj/nWSQuznjmlataTeZNXnu7gJHZkT4FRV0lwewKdhNNaim8iXrQuGl7ylY4nFObSkWIyrkxI4NWqmyTcjrY2pjLn5v9QlJ2orwP0aRN7mUq9P+jXB3LZ7zAvKfpo76Y2tPIq4XER1IrUupqpvfjll4a3VuwNY=,iv:gLXsJtwMHH4cWlStEAvccf/LhXR+oaGW0e2X3oG8RiM=,tag:SnAJnyuQhUoEDgTY+SgX4A==,type:str]
    pgp: []
    encrypted_regex: ^(cloudflare)$
    version: 3.8.1