apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
subjects:
  - name: ingress-nginx-controller
    kind: Service
    spec:
      fqdn: "*.homek8s.cloud"
tunnelRef:
  kind: ClusterTunnel
  name: cloudflare-cluster-tunnel