apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
      interval: 12h
  values:
    fullnameOverride: "prometheus-stack"
    defaultRules:
      create: false
    grafana:
      enabled: true
      persistence:
        enabled: true
        type: pvc
        storageClassName: "longhorn"
        accessModes:
          - ReadWriteOnce
        size: 20Gi
        finalizers:
          - kubernetes.io/pvc-protection
    alertmanager:
      alertmanagerSpec:
        useExistingSecret: true
        configSecret: "alertmanager-prometheus-stack-alertmanager-main"
        replicas: 1
        storage: 
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeEtcd:
      endpoints:
        - 192.168.219.71
        - 192.168.219.72
        - 192.168.219.73 
    prometheus:
      agentMode: true
      prometheusSpec:
        remoteWrite:
        - url: http://kube-thanos-receive.monitoring.svc.talos.home:19291/api/v1/receive
        disableCompaction: true
        externalLabels:
          cluster: talos.home
        retention: 5d
        replicas: 2
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi
            selector: {}
        thanos:
          objectStorageConfig:
            existingSecret:
              name: thanos-objstore-config
              key: objstore.yml  
