apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: thanos-objstore-config
  namespace: monitoring
spec:
  encryptedData:
    objstore.yml: AgBwYHs+hfGZZxkm7y+I6KSVVt0ep22pG7jeL4HJdM6FI7cKxasjFLzVYTQf+YKR7ZPl3i0EJpuK5wmRwh5PJl03PDFR/Kuh7wv+Y2W4ycxxWbMlhgRE7KMkKYhzO7Y8uIkg0kPcOHhrBjX9YIWQy+OT4csIS0G3HhE30mNSo8uXKlKRVocNnY/ChaGcgq2ReVkqXdDyCn9T32drJvxkQHjKqOwwC++ItljX+ONb3xNbDlZsfhxu17VzV1gt1+U8/MWpSrz+SeB+JD9IuQiymELjPq3XMOrU5Kcwd9o4FN4I4U2aw4X+NAMoZydqq7w28Ww/kIft+P5nIsuyh5refHZL+ljIlc6f4ba4b3VClRlL69Pp2zZipWUKESS2HghauD+YInLJ/KubBo0NwIcpjVYNZI1S6+pjSoASqfvEtTaUdJPzjqMYo6KJ5MvfZASR3gRSQY00NRmmuNaX1gks8isvoRenPRbABc1S9LuCvP78B402vUJ47EIQKVLwrHWVOOLROrszbkHNTtM/puVPawCxVeN0HiUVFrMKtc8uEYym3ALYIX12I7CJkQVPktUtML6FUt5QjLNRAX8e9490Y7/qpehZLfVsELewUSNu+2KV4+mnbnjzTpRVVZP0ABlAtECTzCX4hAke9wwxbknDUcXPNjPQblr+50XRAhXNlPU+vDdnDL8SL8fE52R0u2205VrYhB9CyAhiCqVpOqm66iF0bDN6Dr2gVkMkR8g7CbB2fsncKr84AnKVFt5Cj6tROJwhpaJKO60UjpghU+Z9zlX97edFnqZJIWM0r6gJAOe+Cdb7IQJMtX9HzlbwvGzQOfGYqYRZt/J2VnqtFjajp78nFpaUQCAyER93YIMdduW1pM/An8K0ZujBMjKwg7oVT/E2KITe7Q==
  template:
    metadata:
      creationTimestamp: null
      name: thanos-objstore-config
      namespace: monitoring