apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: multus
  namespace: kube-system
spec:
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  interval: 30m
  chart:
    spec:
      chart: multus
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: multus
      interval: 12h
  values:
    image:
      repository: ghcr.io/k8snetworkplumbingwg/multus-cni
      tag: v4.0.2-thick@sha256:3fbcc32bd4e4d15bd93c96def784a229cd84cca27942bf4858b581f31c97ee02
    cni:
      image:
        repository: ghcr.io/angelnu/cni-plugins
        tag: 1.5.1@sha256:caac0fccffb23811386919e3f8cc216de7e1a907648f19bc671d9e495fb77069
      paths:
        config: /etc/cni/net.d
        bin: /opt/cni/bin
    resources:
      requests:
        cpu: 5m
        memory: 70M
      limits:
        memory: 150M
    hostPaths:
      netns: /var/run/netns