apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: multus
  namespace: kube-system
spec:
  interval: 24h
  url: https://helm.cilium.io/https://angelnu.github.io/helm-charts/