apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgAHC31V9gQO53Y8lKoiekw5WaCcVCXLWvVe+QgkBssN+WQb3L2dOsUpLXHVRTM/f/sFiVS2Z7SxOyZdVwyRLbNecoRZX9ihSYqu4xEuEyCH1cB2tcm7l8YU1RUHVks45dee2uwUe7mRwEoewoB8r5xRo2tbCX3uZqVCcBN33BAxsaCLIfsypTCBbQzwv2WIQKhq64kdrl8WyCK5O4pL0yctwO6q0S8RBtGeoYzpiOSPWyg2zrpgbDVwot826R6ep4xPU61BqI6cBQHb5UFxyaNCaCOyUr/KKDIKcXp3A6DKUrH5qTIyiFu70fTW3s+4fBCqKmLNT8GD8pNbR4IOH5XifafNaVqvYKNArr5Q4cxfldUr/vbMdbgGCNptXphdClzUVpe2u8UzA94Ckh3StckGVtbCaiW6dfBR0ZrbW7jWyllMwGwLq1nbetp0D32UjCaYj5t1xh4vlO+WziXZsNYfO3InkB7rjWKDAmH7ZoKpGdkFPviO+MDLuYOg3es3vVA+UO27i4Y4As55MNAGSt0iww7yrTc3pLu8pZZMuQ8IlPKjCIwbFVbvtq/NGMzj2UyOAkWjhvW+Bcqg5LI4VjZU6lWQkla2frouV4CCYlcRTAdhMOjQJg0Iv+WQzLJHPlj2o1+ilrWLuAGGO9Niwprv4q/Vw99trx4Pjdzw11dR89UJ2Riprmtn6UEsNnpTZSaJqCOUoRzeNKOq2RXvwpkXb0uB6Z27llUKlC+ykmTTG2YLMucLJMhhmv9+GmCVSC27akm0U3p73MCOmXvf0W7wHwByUlFGQGYvUBspf89/17qoCn4zohOdXxIqOVw2z90Bh1Z+oeTph8Tc3fDU2R+/338sGpsQ0g1j
  template:
    metadata:
      creationTimestamp: null
      name: discord-url
      namespace: flux-system
    type: Opaque