apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: flux-system
  namespace: flux-system
spec:
  encryptedData:
    password: AgAyj2oJMxa0yiSEtXHsPc8+06Z7LQEpYwH2wgjdotqqxtgrYnkFOpdfUdfnu/5TIAC2a6RYBVt2a6pCxLS/IMV5V0sS3Trj9SXZ6RJbOgiEd/lZOUpneqPEIxK3JCEVYBQJx28kYz4TLT2HQiP2xii+DXUvMcKnH8u8f4APEe0OTjbAQ4hy3QRXty5SQ2T6KjMkbHx0Qt+ib8kP6V22KShKHjtBT+iY1W/jEu5p8uIdI+iKZwlXWtqq+Gw67pxnzUnlPU3FssrWKsYR1xBZKcX/1zXwiGpBhJoYjhNloVtK6QK/s7Jj8MivheaC69fsLgL6hgAgzKsbXgst3/97tNMATaF5ihKZvmdNk/IOhTTxSoXx3SWuE8P3MiAb6v//9tDqeeEAQkMP5Q/JMHs7moPoMZwbTHI4Huw57exFM2NlnuJReB3UNBOt/Tzc2tLxlFIMrPl32CWY2XzRxKnIK5bRJxdU7B+1aflo3rRi421tBNta7gb+IzIDHIY/xbsXvvasknglJKkKikfOT0pIR2feIPbV288JXZxc2+arliih65/2EcRtm3k5i6BQfvG93Xaz5NMWa20PShWud9IOziLnejmGIM/2Vd8MyYzlfU7q+K9WgxrTgL0LHpgE2XRF8K3f5JtEg1YKH2JCsgv+a1iKTvFUynG/5uyGL4EvSseGm+4rMkwh+YGBxEQjqyMglewzWnETSIbcB6lcgZx5FGq+16NafAJ2of5cCvoG9FWZnqCEc28BHPl/
    username: AgBZFPEw5GdNfDp/K+x4xF3JFFojIkM1VDgklm0xwd9tZhGzVbvw8EofMo1ncL9mzITdXCK+gE8ot9PPpc1O83xA2pGKLowCMP8mnqknfUHZYfhpNnAGO1xbqfqP7djNEAsdqa6rEqbQmR3Q6g//+9QUKjwJtanDmVnc8zxsRwqa+saoLX4xk++JeqU+s3kXsBGbnJyJnJZbg/jWIZr2xFCtafi2T5z5e3D3ReMOQd5uuWCrPuRxv7FpUA2av2QZVYfVn3/RG/Bjf8yc/nO0GfSMuHZq0G8eBWs5/XRNZPfOTB4/3KADydNHftVi46KlHNjSf0PwvVE2VyFcywbPXqogn41/XfreGW/wKNvU3wuPKD7ybF/DWii754DrYDs92MA3TKn6sYQrss2yG5Wk8NryFO60KwVcn7hf4lZgsKg9ByrYVHwIQ1BNNXksCh8dtiQfbq8LVZGYnFXg1quNVYL+0hhQgMpFVmIx9+MH8HKVzU5BmiMJlZ2pCzQGC/MglLl0t+eVkirbDMj07ITndJNS/jCkirEB9VN0LpVH8yViw+7OVOCIvOj/I45uhLGd4aRfSD3e626DOkCgqRQcDJr7931/DOCNgLZDlOvs9I/Mmr2gwG6ObbTm+SEfrkU67xw8yV5Us+VOF/srE29DtrvCHj7/KrcxBbx4TugxUpHb6vd8WI9k8ZJYJwTspwbsu2WiHbc=
  template:
    metadata:
      creationTimestamp: null
      name: flux-system
      namespace: flux-system
    type: Opaque